package com.infotech.hibernate;

// Generated Feb 1, 2011 2:27:00 PM by Hibernate Tools 3.2.4.GA

/**
 * Assetdetails generated by hbm2java
 */
public class Assetdetails implements java.io.Serializable {

	private int assetid;
	private Assettype assettype;
	private Login login;
	private Location location;
	private String ipaddress;
	private String compname;
	private String model;
	private String trackingnumber;
	private String monitortrackingnumber;
	private Integer ram;
	private Integer harddisk;
	private String otherassets;

	public Assetdetails() {
	}

	public Assetdetails(int assetid) {
		this.assetid = assetid;
	}

	public Assetdetails(int assetid, Assettype assettype, Login login,Location location,
			String ipaddress, String compname, String model,
			String trackingnumber, String monitortrackingnumber, Integer ram,
			Integer harddisk, String otherassets) {
		this.assetid = assetid;
		this.assettype = assettype;
		this.login = login;
		this.location = location;
		this.ipaddress = ipaddress;
		this.compname = compname;
		this.model = model;
		this.trackingnumber = trackingnumber;
		this.monitortrackingnumber = monitortrackingnumber;
		this.ram = ram;
		this.harddisk = harddisk;
		this.otherassets = otherassets;
	}

	public int getAssetid() {
		return this.assetid;
	}

	public void setAssetid(int assetid) {
		this.assetid = assetid;
	}

	public Assettype getAssettype() {
		return this.assettype;
	}

	public void setAssettype(Assettype assettype) {
		this.assettype = assettype;
	}

	public Login getLogin() {
		return this.login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}

	public String getCompname() {
		return this.compname;
	}

	public void setCompname(String compname) {
		this.compname = compname;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getTrackingnumber() {
		return this.trackingnumber;
	}

	public void setTrackingnumber(String trackingnumber) {
		this.trackingnumber = trackingnumber;
	}

	public String getMonitortrackingnumber() {
		return this.monitortrackingnumber;
	}

	public void setMonitortrackingnumber(String monitortrackingnumber) {
		this.monitortrackingnumber = monitortrackingnumber;
	}

	public Integer getRam() {
		return this.ram;
	}

	public void setRam(Integer ram) {
		this.ram = ram;
	}

	public Integer getHarddisk() {
		return this.harddisk;
	}

	public void setHarddisk(Integer harddisk) {
		this.harddisk = harddisk;
	}

	public String getOtherassets() {
		return this.otherassets;
	}

	public void setOtherassets(String otherassets) {
		this.otherassets = otherassets;
	}

}
