package com.infotech.hibernate;

// Generated Feb 1, 2011 2:27:00 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Assettype generated by hbm2java
 */
public class Assettype implements java.io.Serializable {

	private int assettypeid;
	private String assettypename;
	private Set<Assetdetails> assetdetails = new HashSet<Assetdetails>(0);	

	public Assettype() {
	}

	public Assettype(int assettypeid) {
		this.assettypeid = assettypeid;
	}

	public Assettype(int assettypeid, String assettypename,
			Set<Assetdetails> assetdetails) {
		this.assettypeid = assettypeid;
		this.assettypename = assettypename;
		this.assetdetails = assetdetails;
	}

	public int getAssettypeid() {
		return this.assettypeid;
	}

	public void setAssettypeid(int assettypeid) {
		this.assettypeid = assettypeid;
	}

	public String getAssettypename() {
		return this.assettypename;
	}

	public void setAssettypename(String assettypename) {
		this.assettypename = assettypename;
	}

	public Set<Assetdetails> getAssetdetails() {
		return this.assetdetails;
	}

	public void setAssetdetails(Set<Assetdetails> assetdetails) {
		this.assetdetails = assetdetails;
	}
}
