package com.infotech.hibernate;

// Generated Feb 1, 2011 2:27:00 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private int locationid;
	private String locationname;
	private Set<Login> login = new HashSet<Login>(0);

	public Location() {
	}

	public Location(int locationid) {
		this.locationid = locationid;
	}

	public Location(int locationid, String locationname, Set<Login> login) {
		this.locationid = locationid;
		this.locationname = locationname;
		this.login = login;
	}

	public int getLocationid() {
		return this.locationid;
	}

	public void setLocationid(int locationid) {
		this.locationid = locationid;
	}

	public String getLocationname() {
		return this.locationname;
	}

	public void setLocationname(String locationname) {
		this.locationname = locationname;
	}

	public Set<Login> getLogin() {
		return this.login;
	}

	public void setLogin(Set<Login> login) {
		this.login = login;
	}
}
